trigger:
  batch: true
  branches:
    include:
      - dev
      - main

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  SERVICE_CONNECTION: "choreo-docs-site-dev-sp"

jobs:
  - job: GenerateDocSite
    strategy:
      matrix:
        Python38:
          python.version: '3.8'
    steps:
      - task: usePythonVersion@0
        inputs:
          versionSpec: '3.8'
      - template: templates/build.yaml
      - task: AzureCLI@2
        displayName: Upload files to Azure Storage Account
        env:
          BRANCH_NAME: variables['Build.SourceBranchName']
        inputs:
          azureSubscription: $(SERVICE_CONNECTION)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            if [[ "$BRANCH_NAME" == 'dev' ]]
            then
               az storage blob sync -c '$web/choreo/docs' --account-name "choreodocsdevstorage" -s "$(Build.ArtifactStagingDirectory)/dist/en/"
               az cdn endpoint purge -g choreo-docs-site-rg -n choreodocssitedev --profile-name choreo-docs-dev-cdn --no-wait --content-paths '/*'
            fi

